### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by fizykaa** [Dennis-5618/Popcorn#1]
there is no config token: " token bot" ...

**Comment by Dennis-5618** [comment]
heya, you will need to create a config.json file in your folder and add the following

{
"token": "<Discord token here>",
"database": "<MongoDB token here>"
}

But replace [<Discord token here>](https://www.writebots.com/discord-bot-token/) and [<MongoDB token here>](https://www.mongodb.com/) with your tokens
